/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspbo3;

import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author maaid
 */
public class GUI extends javax.swing.JFrame {
    JFrame frame;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setTitle("Layout");
        frame = new JFrame("Error Msg");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JPanel panel = new JPanel();
        LayoutManager layout = new FlowLayout();  
        panel.setLayout(layout);       
        frame.setSize(560, 200);      
        frame.setLocationRelativeTo(null);  
        nullifiedHasil();
    }
    
    public void nullifiedHasil(){
        stLuasPersegi.setText("");
        stKelilingPersegi.setText("");
        stVolumeBalok.setText("");
        stLuasPermukaanBalok.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stPanjang = new javax.swing.JLabel();
        stLebar = new javax.swing.JLabel();
        stTinggi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        etPanjang = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        etLebar = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        etTinggi = new javax.swing.JEditorPane();
        stHasil = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        stVolumeBalok = new javax.swing.JLabel();
        stLuasPermukaanBalok = new javax.swing.JLabel();
        stKelilingPersegi = new javax.swing.JLabel();
        stLuasPersegi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stPanjang.setText("Panjang");

        stLebar.setText("Lebar");

        stTinggi.setText("Tinggi");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Kalkulator Balok");

        jScrollPane1.setViewportView(etPanjang);

        jScrollPane2.setViewportView(etLebar);

        jScrollPane3.setViewportView(etTinggi);

        stHasil.setText("Hasil : ");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        stVolumeBalok.setText("Volume Balok");

        stLuasPermukaanBalok.setText("Luas Permukaan Balok");

        stKelilingPersegi.setText("Keliling Persegi");

        stLuasPersegi.setText("Luas Persegi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stLebar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stPanjang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(stTinggi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stHasil)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnHitung)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stKelilingPersegi)
                                    .addComponent(stLuasPersegi)
                                    .addComponent(stLuasPermukaanBalok)
                                    .addComponent(stVolumeBalok))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stPanjang)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stLebar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stTinggi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stHasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stLuasPersegi)
                .addGap(18, 18, 18)
                .addComponent(stKelilingPersegi)
                .addGap(18, 18, 18)
                .addComponent(stVolumeBalok)
                .addGap(18, 18, 18)
                .addComponent(stLuasPermukaanBalok)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        /*
        * Input Index 0, 1, 2 = tinggi, lebar, panjang;
        */
        String msg;
        ArrayList<Float> input = new ArrayList<>();
        String[] inputStrings = {
            etTinggi.getText(),
            etLebar.getText(),
            etPanjang.getText()
        };
        try {
            for (int i = 0; i < inputStrings.length; i++) {
                input.add(Float.parseFloat(inputStrings[i]));
            }
            stLuasPersegi.setText(String.valueOf("Luas Persegi      : " + input.get(2) * input.get(1)));
            stKelilingPersegi.setText(String.valueOf("Keliling Persegi      : " + 2 * (input.get(2) + input.get(1))));
            stVolumeBalok.setText(String.valueOf("Volume Balok      : " + input.get(2) * input.get(1) * input.get(0)));
            stLuasPermukaanBalok.setText(String.valueOf("Luas Permukaan Balok       : " + 2 * ((input.get(2) * input.get(1)) + (input.get(1) * input.get(0)) + (input.get(0) * input.get(2)))));
        } catch (Exception e) {
            System.out.println("ex");
            String[] inputTitle = {
                "Tinggi",
                "Lebar",
                "Panjang"
            };
            for (int i = 0; i < inputStrings.length; i++) {
                if (inputStrings[i].isEmpty()) {
                    msg = "Input " + inputTitle[i] + " Kosong!";
                    JOptionPane.showMessageDialog(frame, msg,
                        "Error Msg", JOptionPane.WARNING_MESSAGE);
                     nullifiedHasil();
                }else if(!isNumber(inputStrings[i])){
                    msg = "Input " + inputTitle[i] + " Harus Angka!, Ditemukan \"" + inputStrings[i] + "\"";
                    JOptionPane.showMessageDialog(frame, msg,
                        "Error Msg", JOptionPane.WARNING_MESSAGE);
                     nullifiedHasil();
                }
            }
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private boolean isNumber(String input){
        char[] string = input.toCharArray();
        boolean isNumberic = true;
        for (int i = 0; i < string.length; i++) {
            isNumberic &= Character.isDigit(string[i]);
            if (!isNumberic) {
                break;
            }
        }
        return isNumberic;
    }
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        etLebar.setText("");
        etTinggi.setText("");
        etPanjang.setText("");
        nullifiedHasil();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JEditorPane etLebar;
    private javax.swing.JEditorPane etPanjang;
    private javax.swing.JEditorPane etTinggi;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel stHasil;
    private javax.swing.JLabel stKelilingPersegi;
    private javax.swing.JLabel stLebar;
    private javax.swing.JLabel stLuasPermukaanBalok;
    private javax.swing.JLabel stLuasPersegi;
    private javax.swing.JLabel stPanjang;
    private javax.swing.JLabel stTinggi;
    private javax.swing.JLabel stVolumeBalok;
    // End of variables declaration//GEN-END:variables
}
